### ISSUE TITLE
Update NMS to 1.10?

### ISSUE THREAD

**Issue by Platinteufel** [Cat7373/TuxTwoLib#1]
Hey, is it possible to update the NMS references to 1.10? Seems like Tux2 doesn't do anything at the moment.

**Comment by Cat7373** [comment]
https://github.com/Cat7373/TuxTwoLib/releases/tag/1.10

**Comment by Platinteufel** [comment]
Thanks :)

**Comment by GershonR** [comment]
Will Multiinv work with this version of tux?

**Comment by Cat7373** [comment]
yes

**Comment by GershonR** [comment]
Ok thank you for updating it, it was the last plugin I needed to go 1.10

**Comment by wrecktify** [comment]
MultiInv isn't working right still even when using this latest update.  When switching creative/survival inventories it doesn't separate the inventories anymore.

**Comment by Cat7373** [comment]
@wrecktify 
I confirm the problem

**Comment by Cat7373** [comment]
@wrecktify 
I test forgot to plugin into them.
I did not confirm the problem.

**Comment by GershonR** [comment]
@Cat7373 So Multiinv doesn't work then?

**Comment by Cat7373** [comment]
I have no problem testing

**Comment by GershonR** [comment]
I'll guess it a shot testing, see if it breaks or not

**Comment by GershonR** [comment]
Works fine with multiple accounts, seems to be a problem on his end

1.10-b7 Tux
3.3.6 Multiinv
Spigot 6016ac7-d5ecbd0 (1.10)

**Comment by Cat7373** [comment]
English is not my mother tongue.
Explain more difficult
Let me record a test video.

**Comment by GershonR** [comment]
@Cat7373 No it work good http://i.imgur.com/JgiBvk4.png

**Comment by Cat7373** [comment]
[TuxTwoLib_1.10-b7 + MultiInv3-74 testing](https://youtu.be/MC8bdFy4_hA)

**Comment by Platinteufel** [comment]
Works. Thank you. :)
Hope Tux2 will update it soon though.

**Comment by ghost** [comment]
Thank you very much Cat7373 ! :tada:
